### ISSUE TITLE
Demo for Ex 4

### ISSUE THREAD

**Issue by breadli428** [cmm-21/a5#1]
Hi,

Could you please give an example demo of exercise 4? I kind of implemented something but I am not sure if that's right. It would be super helpful if we have a reference to compare with.

Thanks!

**Comment by eastskykang** [comment]
Hi @breadli428,

I'm actually adding a new simulation scenario (that is way simplified) that you can test collision/contact behaviors: please note, implementing realistic collision simulation is not very straight forward, so our implementation will have many caveat although we implement the logic of impulse-based collision properly. I'm trying to make it more easy to see if you're in a right track or not. 

I will update README and code as soon as possible with a demo video.

**Comment by breadli428** [comment]
Hi Dongho,

Thanks for the reply. Just for your information, for now with purely impulse-based collision implemented, I have to choose the rate to be the maximum allowed value to get a good-looking result. However, my cube will sink under the ground gradually. I am not sure if this is what you refer something "not working well".

But thanks, I will check the update from time to time. Thanks!

**Comment by eastskykang** [comment]
@breadli428 yes that's exactly what I meant. (for epsilon = 0 case) In fact, we need another model for "resting" contacts, but after some discussion with Prof. Stelian Coros, we agreed that this is out of scope. The purpose of Ex.4 is giving you an idea of how to simulate "collision".

I will discuss more details in next tutorial session. 

p.s. please ponder why our impulse-based collision cannot simulate resting contact.

**Comment by eastskykang** [comment]
@breadli428 I hope you managed to complete Ex.4. I'm closing this issue. Please reopen it if there's any issue.
