### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by vullnetu** [cmm-21/a5#10]
I'm confused from this task. My initial thought was to change the integration method and I see that others have done this too but in the tutorial video it was mentioned that this was not what we are supposed to do. Is any method acceptable as long as it solves the issue ?

**Comment by eastskykang** [comment]
Sorry I was misleading. You can change the integration method. What I wanted to say was, you don't need any other damping method (e.g. velocity damping term in spring) for Ex.3.
