### ISSUE TITLE
Can't run a5 on vs-code anymore

### ISSUE THREAD

**Issue by iqiac** [cmm-21/a5#12]
Hello, I'm in big touble. I tried to pull the origin-start-code and accept all current changes. Then when I try to run it in vscode, it doesn't anymore. I tried with deleting and redownloading my repository, still won't work. It still runs the previous projects, just not a5. I also cloned the public a5 repository, didn't work. I don't know why, it just can't build anything.
Seems to be something with the includepaths and eigen libraries.
Any help or suggestions would be welcome.
![image](https://user-images.githubusercontent.com/58211069/117536170-daf2e100-aff9-11eb-80db-d5eaf9ce8c92.png)

**Comment by iqiac** [comment]
In `RBPhysicsEngine.h` it gives me an error at `#pragma once`. It says include-error and I have to update the include-path.

**Comment by iqiac** [comment]
I have no idea how, but it works again... All I did was to `git pull` after waiting a long time.  Afterwards I could run it. I guess magic.

**Comment by hhaofan** [comment]
Maybe you can try to delete it and download a new whole primitive code.
