### ISSUE TITLE
Do we need to recalculate the inertial for cubes?

### ISSUE THREAD

**Issue by BBBBBBob** [cmm-21/a5#14]
Hi,

I have noticed when a sphere is added, its inertial is recalculated based on its radius and mass, but the inertial of the cube is not renewed, So should we also calculate the cube's inertial as the sphere does?

**Comment by eastskykang** [comment]
@BBBBBBob Hi, MOI local of cube is diag(1, 1, 1) (this is reasonable values considering dimension and mass of the cubes). So you don't need to change MOI. But remember, this is local MOI. You should compute MOI expressed in world for Newton-Euler equation.

**Comment by BBBBBBob** [comment]
@eastskykang Thank you for your answer!
