### ISSUE TITLE
Question regarding impulse based collisions

### ISSUE THREAD

**Issue by luohwu** [cmm-21/a5#15]
Hi Dongho

For updating the angular velocity, in the following equation, we considered an additional torque (-w * Iw) due to the rotation of the object itself.
![image](https://user-images.githubusercontent.com/76627876/117640290-28e82000-b185-11eb-9754-1e5933b4e5bc.png)

However, in the following equation, we considered only the external torque. So, I am confused when should we do in the first way and when in the second way.
![image](https://user-images.githubusercontent.com/76627876/117639949-c7c04c80-b184-11eb-86e6-3a0a78bd4924.png)

**Comment by eastskykang** [comment]
Hey, 

please update velocity with external **F**, **t** (tau) as well as **w** x **I** **w** first and then update it with impulse. so you can use **w**<sub>a</sub> instead of **w**'<sub>a</sub> for the **w** x **I** **w** term

**Comment by luohwu** [comment]
aha I see. Thanks
