### ISSUE TITLE
formula for K_a

### ISSUE THREAD

**Issue by lthiet** [cmm-21/a5#17]
hi,

i'm a bit confused about the formula for K_a. 

![image](https://user-images.githubusercontent.com/26815719/117726526-fc64f000-b1e6-11eb-88da-1b663b85ebfc.png)

why is there a cross product without a right operand? or is it r_a_x? but it is not defined..

many thanks

**Comment by benjirer** [comment]
Hey, I was wondering the same thing, did you figure it out?

**Comment by lthiet** [comment]
yes, check out the function `getCrossProductMatrix()`. iirc, you can express the cross product as a skew matrix multiplication, this is what the subscript x mean I think.

**Comment by nwicki** [comment]
Indeed. On the wikipedia page (https://en.wikipedia.org/wiki/Skew-symmetric_matrix) the same notation is also used. The cross product between two vectors a and b (a x b) can be expressed by multiplying b with a matrix initialised with the coefficients of a as depicted here: 
![image](https://user-images.githubusercontent.com/58391419/117828577-3a5b2600-b272-11eb-9855-512696247c8d.png)

Then, we have that a x b = a<sub>x</sub> * b, where a<sub>x</sub> is the skew symmetric matrix of a.

Edit: However, the impulse equation can actually be represented with only using cross products.
