### ISSUE TITLE
Apply external force not working

### ISSUE THREAD

**Issue by swellsc** [cmm-21/a5#21]
Hi, 
I have seen both in the demos and in some issues that there should be the app feature of applying an external force to the object. However, this is not working in my app. I have tried right or left clicking on the object and then dragging the mouse and all it does is move the view of the scene. From the code, it seems that all I should be doing is left-clicking on the object and dragging... Is there something that I am missing to apply this force? Or could I be having compatibility issues with my computer (working on a Mac with a retina screen, which gave issues in some previous assignment)?
Thank you!

**Comment by eastskykang** [comment]
@swellsc 

Hey, if you are using mac with an external screen, that could happen. (I also noticed the same problem, but could not manage to fix it...) 

Please try it with your mac's primary screen and let me know if it works

**Comment by swellsc** [comment]
That was it, it works on the primary screen! Thanks a lot :)
