### ISSUE TITLE
Ex3: blow up of angular velocity after ~10 sec or upon applying force

### ISSUE THREAD

**Issue by stlljonas** [cmm-21/a5#26]
I have adapted the integration scheme both as laid out in lectures and following previous tasks, however I can't seem to get rid of the blow up of the angular velocity. At dt = 1/30, the single mass behaves as expected, but suddenly spins out of control after around 10 seconds with the angular velocity going to infinity. Interestingly this doesn't happen for the coupled masses. Both systems immediately blow up when applying an external force though. I have double checked the implementation of the forces, torques and the integration scheme, but i don't see the issue. Smaller time steps don't seem to improve it either.  Any pointers?

**Comment by eastskykang** [comment]
The very first thing i would do a double check is moment of inertia. You should compute MOI expressed in world frame for solving Newton-Euler equations.

Please briefly review issue #2

**Comment by stlljonas** [comment]
Thank you, that was exactly the issue! I was trying to compute the worldMoI by rotating the localMoI's column vectors using quaternions which is just .. wrong. Everything works as expected now.

**Comment by swellsc** [comment]
Hi, I'm confused about why it seems to be so important to convert from MOI_local to MOI_world. In a general case, of course, but in our case since MOI_local is identity and rotation matrices are orthonormal MOI_world should not change, right? This is, using the formula for changing MOI coordinates given in the rigid body lectures.

> The very first thing i would do a double check is moment of inertia. You should compute MOI expressed in world frame for solving Newton-Euler equations.

**Comment by stlljonas** [comment]
I just looked at the MOI_world in my implementation and I believe you are right, one could get away with skipping the transformation (and inversion) step for this exercise, as they stay the identity throughout. But of course that wouldn't be as rigorous ;) 
In my issue I just somehow managed to mess up the transformation of the identity to itself which broke everything.

**Comment by eastskykang** [comment]
@swellsc @stlljonas you guys are right. I overlooked that the MOI_local is identity (be careful! this is not the case for a collision ball though.)

**Comment by swellsc** [comment]
Thanks a lot for your replies! It makes sense then :)
