### ISSUE TITLE
How to enable slow motion mode?

### ISSUE THREAD

**Issue by Hustwireless** [cmm-21/a5#3]
Hi,

I tried to tick the slowmo checkbox, however it seems that the simulation didn't slow down. Do we need to modify something to make it work?

Thanks!

**Comment by Timothywgraf** [comment]
Hi,

While having the Slow Motion Mode checked, decrease dt via the Simulation Rate track bar to initiate slow motion.

**Comment by eastskykang** [comment]
Slow motion only works for dt < 1.0 / 30

**Comment by Hustwireless** [comment]
It works, thanks!
