### ISSUE TITLE
Stable simulation but inaccurate projectile simulation

### ISSUE THREAD

**Issue by nicolas-git** [cmm-21/a5#9]
For task 3, is it ok for you if the simulation of the springs is stable with the new numerical scheme, but the projectile simulation still has some over or undershoot in its trajectory? or do you expect high accuracy for the projectile too with 30Hz simulation rate?

**Comment by eastskykang** [comment]
This is kind of inevitable. If you see the demo I presented in the tutorial session carefully, there's also *undershoot* in the trajectory.

**Comment by eastskykang** [comment]
Please see this for demo videos: https://github.com/cmm-21/a5/issues/4#issuecomment-833622626

**Comment by nicolas-git** [comment]
Ah okay, I did not watch the demo video... thx ! :)
